### ISSUE TITLE
Mark this project as archived

### ISSUE THREAD

**Issue by squatica** [excalidraw/excalidraw-room#354]
Looks like this project is no longer used at portal.excalidraw.com, so that information is now misleading. It is no longer compatible with the current version of excalidraw/excalidraw. Please mark this project as archived, it will save some time to a lot of people.

**Comment by ad1992** [comment]
Not sure what you mean by incompatible ? This project is the collab server for @excalidraw/excalidraw

**Comment by squatica** [comment]
It was, before this commit: https://github.com/excalidraw/excalidraw/commit/5ca4f5bb - since this commit the app is calling an api `/collab-server`, but this excalidraw-room project doesn't implement such endpoint, it is expecting the websocket connection at `/`. I tested these two projects together and they don't play along. Also the root endpoint of portal.excalidraw.com responds with `server is up` but the root endpoint of this repo prints `Excalidraw collaboration server is up :)` so clearly there is something else running on the actual server.

**Comment by kevintruong** [comment]
any feedback man?

**Comment by kavemang** [comment]
@squatica yes this confused the hell out of me and I spent a bunch of time trying to make the two of these containers work together until I found your post right here

**Comment by ad1992** [comment]
If `REACT_APP_WS_SERVER_URL` is set it uses this server (useful for forks), however in production its a different server that is used by setting `REACT_APP_PORTAL_URL`, check here for [reference](https://github.com/excalidraw/excalidraw/blob/master/src/excalidraw-app/data/index.ts#L70).

However, the source code for the production server is currently private, @dwelle could you share more info on this?

**Comment by agrimpelhuber** [comment]
@kavemang @squatica , I spent some time to figure out what @ad1992 's last comment meant, and I got excalidraw-room working now:

populate `REACT_APP_PORTAL_URL` for production => Uses new /collab-server, closed source (?)
populate `REACT_APP_WS_SERVER_URL` for use of excalidraw-room => uses URL/socket.io/...

These two values are mutually exclusive, or rather: The former beats the latter. So, if you want to use excalidraw-room, leave `REACT_APP_PORTAL_URL` empty. Works for me.

However, what doesn't work for me is turning of the firebase-based persistence. I get a on-screen warning if I leave `REACT_APP_FIREBASE_CONFIG` empty. I could do with *one* warning, and then continue collaborating on a non-persistent basis (maybe have an obtrusive warning on the screen's edge), but what kills it for me is the fact that *the warning box pops up on every change*.

Any clue to turn this off / once-only? I depend on running this without cloud connection.

However, this might seem off-topic, because @squatica 's motion to archive this does not seem to be neccessary

**Comment by dwelle** [comment]
hello. Yes, this project works. As @agrimpelhuber points out, you need to keep `REACT_APP_PORTAL_URL` empty, and use the `REACT_APP_WS_SERVER_URL`. We will actually be removing the `REACT_APP_PORTAL_URL` altogether in the upcoming excalidraw versions. And we're in the process of updating this repo as well (https://github.com/excalidraw/excalidraw-room/pull/355)

----

The persistence to firebase is a separate thing, and its implementation lives in the excalidraw/excalidraw repo (collab.tsx and firebase.ts files).

**Comment by GuillaumeV-cemea** [comment]
@agrimpelhuber If you want to use local storage, there's a [fork here](https://github.com/b310-digital/excalidraw) that implements this :)
